$(".main-offer__offer-slider").wowSlider({
	effect: "basic",
	prev: "",
	next: "",
	duration: 20*100,
	delay: 20*100,
	width: 1024,
	height: 768,
	autoPlay: false,
	autoPlayVideo: false,
	playPause: false,
	stopOnHover: true,
	loop: true,
	bullets: 1,
	caption: true,
	captionEffect: "fade",
	controls: true,
	controlsThumb: false,
	responsive: 2,
	fullScreen: false,
	gestures: 2,
	onBeforeStep: 0,
	images: 0
});